This is makeindex, version 2.16 [TeX Live 2022] (kpathsea + Thai support).
Scanning style file ./main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main.acn....done (11 entries accepted, 0 rejected).
Sorting entries....done (39 comparisons).
Generating output file main.acr....done (26 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
